theme: jekyll-theme-minimal
title: 'PacBio Iso-Seq Workshop Online'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule
  - heading: Support
  - title: Using Slack in this workshop
    url: base/slack
  - title: Using Zoom in this workshop
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - heading: Command Line Interface
  - title: Logging In and Transferring Files
    url: CLI/logging-in
  - title: Intro CLI
    url: CLI/command-line-intro
  - title: Advanced CLI
    url: advanced-command-line
  - title: Advanced CLI Challenge Solutions
    url: advanced-challenge-solutions
  - title: Clusters and Modules
    url: cluster 
